# Generated by Django 4.1.13 on 2024-07-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newinterface",
            name="host",
            field=models.CharField(
                blank=True, help_text="域名", max_length=100, null=True, verbose_name="域名"
            ),
        ),
    ]
