# Generated by Django 4.1.13 on 2024-07-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_newinterface_host"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newinterface",
            name="host",
            field=models.JSONField(
                blank=True, default=dict, help_text="域名", verbose_name="域名"
            ),
        ),
    ]
