# Generated by Django 4.1.13 on 2024-07-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_newinterface_host"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testenv",
            name="global_func",
            field=models.TextField(
                blank=True,
                default='# -*- coding: utf-8 -*-\n# @author: HRUN\n\n"""\n自定义全局工具函数\n============================\n"""\nfrom apitestengine.core.tools import *\n',
                help_text="用例工具文件",
                null=True,
                verbose_name="用例工具文件",
            ),
        ),
    ]
