# Generated by Django 4.1.13 on 2024-07-18 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "testplans",
            "0003_remove_testscene_project_remove_teststep_interface_and_more",
        ),
        ("projects", "0004_alter_testenv_global_func"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Interface",
        ),
    ]
