# Generated by Django 4.1.13 on 2024-07-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_mock_mockdetail_mocklog_mockdetailform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mockdetail",
            name="config",
            field=models.JSONField(
                blank=True, default=dict, help_text="配置", verbose_name="配置"
            ),
        ),
        migrations.AlterField(
            model_name="mockdetail",
            name="response",
            field=models.JSONField(
                blank=True, default=dict, help_text="响应体", verbose_name="响应体"
            ),
        ),
    ]
