# Generated by Django 4.1.13 on 2024-07-18 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_alter_mockdetail_config_alter_mockdetail_response"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mock",
            name="newInterface",
            field=models.OneToOneField(
                help_text="接口id",
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.newinterface",
                verbose_name="mock",
            ),
        ),
        migrations.AlterField(
            model_name="mockdetail",
            name="mock",
            field=models.ForeignKey(
                help_text="mock",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="MockDetail",
                to="projects.mock",
            ),
        ),
        migrations.AlterField(
            model_name="mockdetailform",
            name="mockDetail",
            field=models.ForeignKey(
                help_text="mock详情",
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.mockdetail",
                verbose_name="mockDetailForm",
            ),
        ),
    ]
