# Generated by Django 4.1.13 on 2024-07-18 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_alter_mock_newinterface_alter_mockdetail_mock_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mockdetailform",
            name="mockDetail",
            field=models.ForeignKey(
                help_text="mock详情",
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.mockdetail",
                verbose_name="detailForm",
            ),
        ),
    ]
