# Generated by Django 4.1.13 on 2024-07-19 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_alter_mockdetailform_mockdetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mockdetailform",
            name="mockDetail",
            field=models.ForeignKey(
                help_text="mock详情",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detailForm",
                to="projects.mockdetail",
            ),
        ),
    ]
