# Generated by Django 4.1.13 on 2024-07-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_alter_mockdetailform_mockdetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="mock",
            name="method",
            field=models.CharField(
                default=1, help_text="请求方法", max_length=50, verbose_name="请求方法"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mock",
            name="name",
            field=models.CharField(
                default=1, help_text="接口名称", max_length=50, verbose_name="接口名"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mock",
            name="path",
            field=models.CharField(
                default=1, help_text="接口路径", max_length=200, verbose_name="接口路径"
            ),
            preserve_default=False,
        ),
    ]
