# Generated by Django 4.1.13 on 2024-07-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0012_mock_method_mock_name_mock_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="mockdetail",
            name="conditionForm",
            field=models.JSONField(
                blank=True, default=list, help_text="条件", verbose_name="条件"
            ),
        ),
        migrations.DeleteModel(
            name="MockDetailForm",
        ),
    ]
