# Generated by Django 4.1.13 on 2024-07-20 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_mockdetail_conditionform_delete_mockdetailform"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mock",
            old_name="path",
            new_name="url",
        ),
    ]
