# Generated by Django 4.1.13 on 2024-07-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_rename_path_mock_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mock",
            name="status",
            field=models.BooleanField(default=False, verbose_name="状态"),
        ),
    ]
