# Generated by Django 4.1.13 on 2024-07-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0015_alter_mock_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="mockdetail",
            name="ipInput",
            field=models.CharField(
                blank=True,
                help_text="生效ip",
                max_length=50,
                null=True,
                verbose_name="生效ip",
            ),
        ),
        migrations.AlterField(
            model_name="mockdetail",
            name="ipCode",
            field=models.BooleanField(default=False, verbose_name="是否开启生效ip"),
        ),
    ]
