# Generated by Django 4.1.13 on 2024-05-31 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="project",
            field=models.ManyToManyField(
                blank=True,
                default="",
                help_text="项目",
                null=True,
                related_name="users",
                to="projects.project",
            ),
        ),
    ]
