# Generated by Django 4.1.13 on 2024-05-31 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("users", "0002_alter_user_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="project",
            field=models.ManyToManyField(
                help_text="项目", related_name="users", to="projects.project"
            ),
        ),
    ]
