# Generated by Django 4.1.13 on 2024-07-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testplans", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stepcontroller",
            name="dlg",
            field=models.BooleanField(
                default=False, help_text="循环控制器是否展开", verbose_name="循环控制器是否展开"
            ),
        ),
        migrations.AlterField(
            model_name="stepcontroller",
            name="inputDlg",
            field=models.BooleanField(
                default=False, help_text="自定义脚本是否展开", verbose_name="自定义脚本是否展开"
            ),
        ),
    ]
