# Generated by Django 4.1.13 on 2024-07-18 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testplans", "0002_alter_stepcontroller_dlg_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testscene",
            name="project",
        ),
        migrations.RemoveField(
            model_name="teststep",
            name="interface",
        ),
        migrations.RemoveField(
            model_name="testplan",
            name="scenes",
        ),
        migrations.DeleteModel(
            name="SceneData",
        ),
        migrations.DeleteModel(
            name="TestScene",
        ),
        migrations.DeleteModel(
            name="TestStep",
        ),
    ]
